name: Package and Docs Deployment


on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:


permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            cache-version: 1
            packages: |
                bookdown
                gridExtra
                UpSetR
                pROC
                plotly
                testthat
                future
                future.apply
                progress
                progressr
                edgeR

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.cmdstan
          key: ${{ runner.os }}-cmdstan

      - name: Install STAN
        run: |
          Rscript -e '
            install.packages("cmdstanr", repos = c("https://stan-dev.r-universe.dev", getOption("repos")))
            cmdstanr::install_cmdstan()
          '

      - name: Build and install hespresso package
        run: |
          R CMD build .
          PACKAGE_FILE=$(ls hespresso_*.tar.gz)
          R CMD INSTALL $PACKAGE_FILE
          echo "PACKAGE_FILE=$PACKAGE_FILE" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.PACKAGE_FILE }}

      - name: Build docs
        run: |
          cd docs
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_html'

      - uses: actions/deploy-pages@v4

